version: '3'

services:
  node:
    image: arm32v7/iroha-pi
    ports:
      - "50051:50051"
    environment:
      - IROHA_POSTGRES_USER=postgres
      - IROHA_POSTGRES_PASSWORD=HelloW0rld
      - CCACHE_DIR=/tmp/ccache
    depends_on:
      - redis
      - postgres
    volumes:
      - /usr/local/src/github.com/tkyonezu/iroha-pi/example:/opt/iroha/config
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha

  postgres:
    image: arm32v7/postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - IROHA_POSTGRES_PASSWORD=HelloW0rld
    depends_on:
      - redis

  redis:
    image: arm32v7/redis

volumes:
  ccache-data:
