# Copyright Takeshi Yonezu. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:

  node1:
    image: arm32v7/${IROHA_IMG}
    container_name: iroha-node1
    restart: always
    ports:
      - "50051:50051"
    environment:
      - IROHA_CONF=iroha1.conf
      - IROHA_NODE=node1
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/block_store1:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    depends_on:
      - postgres1

  node2:
    image: arm32v7/${IROHA_IMG}
    container_name: iroha-node2
    restart: always
    environment:
      - IROHA_CONF=iroha2.conf
      - IROHA_NODE=node2
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/block_store2:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    depends_on:
      - postgres2

  node3:
    image: arm32v7/${IROHA_IMG}
    container_name: iroha-node3
    restart: always
    environment:
      - IROHA_CONF=iroha3.conf
      - IROHA_NODE=node3
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/block_store3:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    depends_on:
      - postgres3

  node4:
    image: arm32v7/${IROHA_IMG}
    container_name: iroha-node4
    restart: always
    environment:
      - IROHA_CONF=iroha4.conf
      - IROHA_NODE=node4
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/block_store4:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    depends_on:
      - postgres4

  postgres1:
    image: arm32v7/postgres:9.5
    container_name: iroha-postgres1
    restart: always
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

  postgres2:
    image: arm32v7/postgres:9.5
    container_name: iroha-postgres2
    restart: always
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

  postgres3:
    image: arm32v7/postgres:9.5
    container_name: iroha-postgres3
    restart: always
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

  postgres4:
    image: arm32v7/postgres:9.5
    container_name: iroha-postgres4
    restart: always
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

volumes:
  ccache-data:
