version: '3'

services:
  node:
    image: hyperledger/iroha-pi
    ports:
      - "50051:50051"
    environment:
      - IROHA_POSTGRES_HOST=${COMPOSE_PROJECT_NAME}_postgres_1
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=HelloW0rld
      - IROHA_REDIS_HOST=${COMPOSE_PROJECT_NAME}_redis_1
      - IROHA_REDIS_PORT=6379
      - CCACHE_DIR=/tmp/ccache
    depends_on:
      - redis
      - postgres
    tty: true
    volumes:
      - ../example:/opt/iroha/config
      - ../../iroha/build/test_bin:/opt/iroha/test_bin
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=HelloW0rld
    depends_on:
      - redis

  redis:
    image: redis:3.2.8

volumes:
  ccache-data:
