# Copyright Takeshi Yonezu. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:
  node:
    image: arm32v7/${IROHA_IMG}
    ports:
      - "50051:50051"
      - "10001:10001"
    environment:
      - IROHA_NODE=kubenode3
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/block_store:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    depends_on:
      - postgres

  postgres:
    image: arm32v7/postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

volumes:
  ccache-data:
